server:
  port: 30000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tNWcE25KmKP2PUHwQD3
      secret-key: dK0xmM7GGhcrV7TW2qaII29Zllaeli
      oss:
        endpoint: oss-cn-qingdao.aliyuncs.com
        bucket: gulimall---zch
      host: https://dfsns.market.alicloudapi.com
      path: /data/send_sms
      appcode: 4f6116e262c54dc49551e65d2667fa03

  application:
    name: gulimall-thirdpart